version: "3.9"
services:
  jellyfin:
    image: ghcr.io/aleksasiriski/jellyfin-rffmpeg:latest
    environment:
      - TZ=Europe/Berlin
      # - DATABASE_TYPE=postgres
      # - DATABASE_HOST=localhost
      # - DATABASE_PORT=5432
      # - DATABASE_NAME=rffmpeg
      # - DATABASE_USERNAME=postgres
      # - DATABASE_PASSWORD=supersecurepassword
    ports:
      - ${JELLYFIN_LAN_ONLY_IP:-}:8096:8096 # public should access via reverse proxy
    volumes:
      - jellyfin-conf:/config:z
      - /var/storage/media:/var/storage/media # optional media folder
    restart: always
  nfs-server:
    image: ghcr.io/obeone/nfs-server:latest
    cap_add:
      - SYS_ADMIN
    environment:
      - TZ=Europe/Berlin
      - NFS_EXPORT_0="/config/transcodes      *(rw,sync,no_subtree_check,no_root_squash)"
      - NFS_EXPORT_1="/config/data/subtitles  *(rw,sync,no_subtree_check,no_root_squash)"
      - NFS_EXPORT_2="/var/storage/media      *(rw,sync,no_subtree_check,no_root_squash)" # optional media folder
    ports:
      - ${JELLYFIN_LAN_ONLY_IP:-}:2049:2049
    volumes:
      - jellyfin-conf:/config:z
      - /var/storage/media:/var/storage/media # optional media folder
    restart: always
volumes:
  jellyfin-conf: